import os

DEFAULT_PRODUCT_NAME = "Settra"

PRODUCT_NAME = os.getenv("PRODUCT_NAME", DEFAULT_PRODUCT_NAME).strip()
AI_CLIENT_DESCRIPTION = os.getenv("AI_CLIENT_DESCRIPTION", "").strip()

if not PRODUCT_NAME:
    PRODUCT_NAME = DEFAULT_PRODUCT_NAME
