import os

from app.common.config import DATA_DIR

STEAMPIPE_HOST = os.getenv("STEAMPIPE_HOST", "steampipe")
STEAMPIPE_PORT = int(os.getenv("STEAMPIPE_PORT", "9193"))
STEAMPIPE_DB_PASSWORD = os.getenv("STEAMPIPE_DB_PASSWORD", "")
MAX_RESULT_ROWS = int(os.getenv("CHAT_MAX_RESULT_ROWS", "100"))
MAX_QUERY_ATTEMPTS = int(os.getenv("CHAT_MAX_QUERY_ATTEMPTS", "5"))

TABLE_SAMPLE_ROWS = 3
TABLE_SAMPLE_MAX_COLUMNS = 24
TABLE_SAMPLE_VALUE_MAX_CHARS = 180
GOOGLE_SHEETS_CELL_SAMPLE_ROWS = 8
GOOGLE_SHEETS_CELL_SAMPLE_MAX_CELLS = 160
GOOGLE_SHEETS_SYSTEM_COLUMNS = {"sp_connection_name"}

HISTORY_MESSAGE_LIMIT = 12
HISTORY_RESULT_CONTEXT_LIMIT = 3
